#!/bin/sh
# (c) bohoomil
if [ $? -ne 0 ]; then
  edit='termite -e vim -T screen-256color'
else
  edit='termite -e vim -T screen-256color'
fi

if [ ! -f "$1" ]; then
	$edit
else
	$edit "$1"
fi

exit 0

