#!/usr/bin/env bash
## xvim - used to open termite with (neo)vim in X
if [ command -v nvim >/dev/null 2>&1 ]; then
    $VIM="nvim"
elif [ command -v vim >/dev/null 2>&1 ]; then
    $VIM="vim"
else
    $VIM="vi"
fi

if [ $? -ne 0 ]; then
  edit='termite -e $VIM -T screen-256color'
else
  edit='termite -e $VIM -T screen-256color'
fi

if [ ! -f "$1" ]; then
	$edit
else
	$edit "$1"
fi

exit 0

